# @package _global_
hydra:
  callbacks:
    cactus_plot:
      _target_: src.callbacks.plotting_callbacks.CactusPlot
      combine_multiple_runs: False
      runtime_key: user_sys_time # perfcounter_time or user_sys_time